import { gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import client from "../gql/client";
import AnimeCard from "./components/AnimeCard";

const Home: NextPage<{ animes: any[] }> = ({ animes }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
        {animes.map((anime) => (
          <AnimeCard key={anime.id} anime={anime} />
        ))}
      </div>
    </>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query {
        Page {
          media(sort: POPULARITY_DESC, type: ANIME) {
            id
            title {
              userPreferred
            }
            coverImage {
              extraLarge
            }
            episodes
          }
        }
      }
    `,
  });

  return {
    props: {
      animes: data.Page.media,
    },
  };
}

export default Home;
